### ISSUE TITLE
License

### ISSUE THREAD

**Issue by phit** [CreeperHost/modpacklauncher#1]
Please don't use Creative Commons for software, even the foundation recommends against doing so.

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by ThePaul-T** [comment]
Hello, phit,

Thank you for your concern.

Unfortunately, their reasoning for not using their license for software does not appear to apply in this use case.

A decision was made to make this visible source but not open; we chose this license as it was more open than just all rights reserved, as we wanted people to be able to download and modify this for personal use, but not share/distribute it.

We cannot find another license compatible with our vision; as such, we chose this license.

Stay safe.

**Comment by ThePaul-T** [comment]
Okay, so, seeing these reactions, I feel you deserve an explanation of my selfish reasons why.

I am not happy with it in its current state, and I want **us** to be the ones who fix it to the point it's something to be proud of. Until that point, I do not want anyone else basing any of their own projects off it.

We will finish it, and at the moment, my goal is to (likely with the help of people we know) get this to that state ASAP then relax the license.

But after spending significant amounts of paid staff time on this (We ran into JRE bugs and all sorts...) and a whole lot more out of hours (Myself and others), I do not want to see the majority of our work replaced with someone else's (better) work, it would be soul-destroying for us all.

I KNOW this is a terrible reason, but it's my reason and I hope you all respect it and hold me to my world to relax the licensing once this code has better error handling and better structure.

**Comment by ThePaul-T** [comment]
Closing this now as we've reached the point we're happy enough with the flow, and as such we've merged this backend code into the main app repo available at https://github.com/FTBTeam/FTB-App and it now comes under the license there.
