### ISSUE TITLE
How exactly do you build?

### ISSUE THREAD

**Issue by ramirocantu** [CreeperHost/modpacklauncher#11]
Hi I'm trying to build the modpacklauncher for the purpose of packaging for personal flatpak. I stumbled into the gradlew tasks and by default gradlew build ftpRelease attempts to build for all platforms, in the meantime however I changed the node script to just build for linux. Then media task fails because I need to install "install4j" and that requires a license. 

Sorry for the rambling, I'm just a little confused as to what the building and packaging procedure is for linux, I would really appreciate some pointers.

**Comment by ThePaul-T** [comment]
We use install4j to build platform binaries and installers.

For what you’re trying to do, you may be better modifying https://github.com/CreeperHost/modpacksch-serverdownloader to download the client forge installer and ignore the client only flag.

________________________________

**Comment by ramirocantu** [comment]
Ahh I see that now, thank you so much for quick reply

**Comment by ThePaul-T** [comment]
No problem. It’s 9am here :)

________________________________

**Comment by ramirocantu** [comment]
I was wondering if there was a way to build the java backend exclusively without an npm build; essentially a gradle task equivalent of ./gradlew ShadowDistTar without building the electron app.
