### ISSUE TITLE
OS X version deletes all saved files, modpacks and installed Minecraft versions when it self-updates

### ISSUE THREAD

**Issue by benevolentmadman** [CreeperHost/modpacklauncher#12]
When running the launcher on OS X, it deletes everything when it self updates. It is storing the save files, installed modpacks, and downloaded Minecraft versions inside the `.app` package, which gets entirely replaced upon update.

The standard location for custom application data on OS X would be `~/Library/Application Support/FTBApp/`, and the user's data that should not be lost should be kept there.

more details available here https://github.com/FTBTeam/FTB-App/issues/90

**Comment by ThePaul-T** [comment]
This is exactly what the release last night fixed, we rewrote parts of the app to use user.dir instead of cwd.
