### ISSUE TITLE
Cannot install with weird characters as a folder name.

### ISSUE THREAD

**Issue by upedd** [CreeperHost/modpacklauncher#13]
I couldn't install the app because my windows username contains polish "Ł" character. 
There was this error message while starting the app: 
`The JVM could not be started. The maxiumum heap size (-Xmx) might be too large or an antivirus or firewall tool could block the execution.`
Installing in other place fixed it.

**Comment by gigabit101** [comment]
I belave this has already been fixed, If the issue continues feel free to re-open the issue
