### ISSUE TITLE
Cannot download some mods

### ISSUE THREAD

**Issue by vitSkalicky** [CreeperHost/modpacklauncher#16]
This is probably a bug with mod downloading API.

When I download a modpack using the official launcher everything seems fine. But when I launch the modpack, forge reports missing dependencies, because some mods weren't downloaded. When I use the latest build of multiMC, which also supports the new FTB modpacks, I get this error while downloading modpack:
```
Job 'Mod download' failed to process:
https://dist.modpacks.ch/aroma1997/core/unknown/Aroma1997Core-1.12.2-2.0.0.2.jar
https://dist.modpacks.ch/com/valkyrieofnight/et/1.12.2-2.0.20.1/environmentaltech-1.12.2-2.0.20.1.jar
https://dist.modpacks.ch/com/valkyrieofnight/um/1.12.2-1.0.16.1/valkyrielib-1.12.2-2.0.20.1.jar
https://dist.modpacks.ch/it/zerono/mods/zerocore/internal/1.12.2-0.1.2.8/zerocore-1.12.2-0.1.2.8.jar
https://dist.modpacks.ch/magicbees/3.1.10/MagicBees-1.12.2-3.1.10.jar
https://dist.modpacks.ch/mcjty/rftoolscontrol/2.0.2/rftoolsctrl-1.12-2.0.2.jar
https://dist.modpacks.ch/mod/chiselsandbits/core/14.33/chiselsandbits-14.33.jar
https://dist.modpacks.ch/net/bdew/gendustry/1.6.5.8/gendustry-1.6.5.8-mc1.12.2.jar
```
These URL addresses returns `404 page not found`.

However, most mods, for example Extra Utilities (`https://dist.modpacks.ch/com/rwtema/extrautils2/1.0/extrautils2-1.12-1.9.9.jar`), are downloaded just fine.

**Comment by ThePaul-T** [comment]
It's either one of two issues.

A bad import when the pack was pulled over (No real way to check as we've no idea which of several hundred imports we have you're using) or some file corruption (had a strange file system issue after a raid card error recently)

@Rushmead has a better chance of knowing this.

**Comment by gigabit101** [comment]
I belave this has already been fixed, If the issue continues feel free to re-open the issue
