### ISSUE TITLE
Linux downloader crashes on large packs (3.5k files, FTB Interactions)

### ISSUE THREAD

**Issue by ananace** [CreeperHost/modpacklauncher#17]
With the downloader from `https://api.modpacks.ch/public/modpack/5/121/server/linux`, any attempt to install the pack FTB Interactions (with its 3.5k files) seems to fail around file 2100-3400, with a threading error.
This happens on all systems tested.

The error is `Fatal error: PosixJavaThreads.start0: pthread_create`, along with a lot of crash info.

The combined stdout+stderr output for such a crash looks like; [combined.log](https://github.com/CreeperHost/modpacklauncher/files/5325278/combined.log)

**Comment by ThePaul-T** [comment]
Is this only interactions?
________________________________

**Comment by ananace** [comment]
I haven't tested every possible modpack ID, but of the FTB ones Interactions seems to be the only pack with enough files for it to fail.

My guess is that the futures for downloading run into issues with over 2k of them active at the same time.

**Comment by ThePaul-T** [comment]
Interesting, I'll assume I never went back to this and implemented a thread pool as we did in the client app, I'll sort it this coming working week.

Kind of want to rewrite this honestly, it was done in the 48 hours before the release between working on the client app as I managed to forget it was important when focusing on the app, a little terrible form from a company that relies on servers.

**Comment by dasmou** [comment]
> 
> 
> Interesting, I'll assume I never went back to this and implemented a thread pool as we did in the client app, I'll sort it this coming working week.
> 
> Kind of want to rewrite this honestly, it was done in the 48 hours before the release between working on the client app as I managed to forget it was important when focusing on the app, a little terrible form from a company that relies on servers.

Nice, thanks for uploading! i just found this thread when i had the same problems :P

**Comment by gigabit101** [comment]
I belave this has already been fixed, If the issue continues feel free to re-open the issue
