### ISSUE TITLE
Unable to download correctly server files

### ISSUE THREAD

**Issue by vipongo** [CreeperHost/modpacklauncher#19]
I downloaded the FTB university server installer and launched it
After everything installed, I launched the server
However, my quest book is empty. By empty, I mean there is nothing on it
I joined a team, restarted my client and the server. The files from the quest book were not downloaded

I noticed during the installation a big number of files that couldn't be downloaded.

After trying another time, the server.jar was not even downloaded.

My internet connection is great (fiber optics without any lags)

**Comment by gigabit101** [comment]
This issue should have been posted on https://github.com/CreeperHost/modpacksch-serverdownloader
