### ISSUE TITLE
Can't download Minecraft launcher on Linux if /tmp is on a different filesystem

### ISSUE THREAD

**Issue by Aneurin** [CreeperHost/modpacklauncher#20]
In `McUtils::downloadVanillaLauncher()`, the call to `destinationFile.canWrite()` will never return true since the file doesn't exist yet, so it always falls back to trying to download it to a temporary location. Once it's downloaded, it then tries to move it to the destination by calling `destinationFile.renameTo()`. Unfortunately, that call doesn't seem to work on Linux if `/tmp/` is not on the same filesystem as `$HOME/.ftba/`, which is a common setup.

I think this could probably be fixed by checking `canWrite()` for the destination *directory*, rather than the non-existent file. Alternatively, it could be handled by not checking and trying anyway, handling any exceptions and seeing if the process was successful afterwards.

For my own purposes, I went through the remaining setup steps manually to get this running for me, but I thought it would be worth reporting in case anyone else is affected.

**Comment by ThePaul-T** [comment]
Hi there,

Thanks for the report, that is actually fixed in our internal testing version, and I thought it would be fixed in the publicly released version, we’ve just not merged the changes down the branches just yet.

Paul

**Comment by gigabit101** [comment]
We have pushed out multiple updates since this issue was posted, The handler for downloading the Minecraft Launcher has been completely redone, If this issue continues please do let us know.
