### ISSUE TITLE
App hanging on Creating Environment

### ISSUE THREAD

**Issue by LoganMReber** [CreeperHost/modpacklauncher#24]
I have tried multiple times and have been stuck on this step for 20+ minutes.

![image](https://user-images.githubusercontent.com/4927951/107982084-04671800-6f89-11eb-8d21-96f295c26664.png)

**Comment by gigabit101** [comment]
Can you try this again using the latest version of the App? We rolled out an update that might have resolved this issue, If the issue continues please re-open this issue with the launchers log files
