### ISSUE TITLE
Launcher Tray coremod is not marked as client-side-only

### ISSUE THREAD

**Issue by JoJoDeveloping** [CreeperHost/modpacklauncher#25]
See https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/215

Basically, your coremod which you download here:
https://github.com/CreeperHost/modpacklauncher/blob/78a210f56c9ad6dec3ffe5012143bed92eff2a88/src/main/java/net/creeperhost/creeperlauncher/pack/LocalInstance.java#L412-L422 is not marked as client-side-only (see https://mcforge.readthedocs.io/en/1.15.x/concepts/sides/#writing-one-sided-mods) and thus causes the red "incompatible server" thingy to be shown by the client because it expects your mod on the server.

Also, just a request: Since mods in general and coremods in particular do hacky stuff that make debugging hard, MC Forge would appreciate it if you at least made your coremod visible-source. Or you remove the "testing code" [here](https://github.com/CreeperHost/modpacklauncher/blob/78a210f56c9ad6dec3ffe5012143bed92eff2a88/src/main/java/net/creeperhost/creeperlauncher/pack/LocalInstance.java#L408), which forces this coremod into every modpack (on windows).

**Comment by gigabit101** [comment]
Moved this issue over to the launcher tray mod project
