### ISSUE TITLE
Can't use old installed modpack

### ISSUE THREAD

**Issue by PrincedelaLune** [CreeperHost/modpacklauncher#6]
Hi, I just downloaded the new launcher put i cant figure out how to play with an already downloaded modpack ... I was using the old ftb launcher and I can't find a way to tell the new launcher that the file of the modpack i have are "there".
Gonna continue using old one for now, my internet connection is limited and and my disk space too :p
Keep up with good work !
btw: love the new design :D

**Comment by TheExistingOne** [comment]
My understanding of the new launcher is that you'll have to re-download them. However since it installs them as a normal modded Minecraft install you could copy your worlds over.

**Comment by Cloudhunter** [comment]
Pretty much - not supposed to be able to use old modpacks as they will be in a different format and launched differently.
