### ISSUE TITLE
FTBApp provides a redundant JRE install

### ISSUE THREAD

**Issue by shinji257** [CreeperHost/modpacklauncher#8]
Currently the FTBApp is providing a redundant JRE install that isn't use (as best as I can tell).  When the vanilla Minecraft launcher is run the JRE retrieved by the vanilla launcher is used instead of the one that is provided by FTBApp.

EDIT: Just found out it is used for pack installs but can we try to not have 2 JRE installs somehow?

**Comment by Cloudhunter** [comment]
Not really. We need at least Java 11 for functionality of the app, and most modpacks won't run with Java 11 yet - and Vanilla Minecraft and Forge only officially support Java 8. Not really any way round two JRE's without rewriting a huge part of it. Compared to sizes of most packs though, it isn't a big issue.
